---
title: "Milestone 4"
author: "Wenyi Shao"
date: "`r Sys.Date()`"
output: 
  html_document: 
    toc: true
    fig_width: 8
    fig_height: 8
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Load libraries and file from Milestone 3
```{r libraries, message=FALSE, warning=FALSE}
library(clusterProfiler)
library(DOSE)
library(org.Hs.eg.db)
library(AnnotationDbi)
library(ggplot2)
```

```{r load}
load("C:/Users/hwenn/ANGSD/Project.RData")
```

### Gene ontology enrichment analysis
```{r GO}
DGE_genes_1 <- subset(df_result_1, padj < 0.05)
DGE_genes_1 <- DGE_genes_1[order(DGE_genes_1$padj), ]
head(DGE_genes_1)

DGE_genes_2 <- subset(df_result_2, padj < 0.05)
DGE_genes_2 <- DGE_genes_2[order(DGE_genes_2$padj), ]
head(DGE_genes_2)

organism <- "org.Hs.eg.db"
res_go_1 <- enrichGO(gene=rownames(DGE_genes_1),
                   universe=dds_genes_rownames,
                   ont="ALL",
                   keyType="SYMBOL",
                   minGSSize = 3,
                   maxGSSize = 800,
                   pvalueCutoff = 0.05,
                   OrgDb = organism,
                   pAdjustMethod = "BH")

res_go_2 <- enrichGO(gene=rownames(DGE_genes_2),
                   universe=dds_genes_rownames,
                   ont="ALL",
                   keyType="SYMBOL",
                   minGSSize = 3,
                   maxGSSize = 800,
                   pvalueCutoff = 0.05,
                   OrgDb = organism,
                   pAdjustMethod = "BH")
```

### Run REVIGO
The tables for REVIGO were generated and analyzed using the website. However, there were no gene sets that specifically stand out.
```{r resgoObj}
res_go_1[1, ] %>% str
sig_gene_1 <- unlist(strsplit(res_go_1[1, "geneID"], "/"))
head(sig_gene_1)
write.table(res_go_1@result[ , c("ID", "pvalue")],
            file="enrichGO-1.txt", sep="\t",
            quote=FALSE, row.names=FALSE)

res_go_2[1, ] %>% str
sig_gene_2 <- unlist(strsplit(res_go_2[1, "geneID"], "/"))
head(sig_gene_2)
write.table(res_go_2@result[ , c("ID", "pvalue")],
            file="enrichGO-2.txt", sep="\t",
            quote=FALSE, row.names=FALSE)
```

### Run gene set enrichment analysis
```{r gse}
gene_list_1 <- df_result_1$log2FoldChange
names(gene_list_1) <- rownames(df_result_1)
gene_list_1 <- sort(gene_list_1, decreasing = TRUE)
head(gene_list_1)

gse_1 <- gseGO(geneList=gene_list_1,
             ont ="ALL",
             keyType = "SYMBOL",
             minGSSize = 3,
             maxGSSize = 800,
             pvalueCutoff = 0.05,
             verbose = TRUE,
             OrgDb = organism,
             pAdjustMethod = "BH")

gene_list_2 <- df_result_2$log2FoldChange
names(gene_list_2) <- rownames(df_result_2)
gene_list_2 <- sort(gene_list_2, decreasing = TRUE)
head(gene_list_2)

gse_2 <- gseGO(geneList=gene_list_2,
             ont ="ALL",
             keyType = "SYMBOL",
             minGSSize = 3,
             maxGSSize = 800,
             pvalueCutoff = 0.05,
             verbose = TRUE,
             OrgDb = organism,
             pAdjustMethod = "BH")
```

### Dot plots for GSE and most enriched gene sets
```{r gseObj}
dotplot(gse_1, showCategory=10, split=".sign") + facet_grid(.~.sign) + theme(axis.text.y = element_text(size = 10), text = element_text(size = 14))
gseaplot(gse_1, by = "all", title = gse_1$Description[1], geneSetID = 1)

options(repr.plot.width = 7, repr.plot.height = 9)
dotplot(gse_2, showCategory=10, split=".sign") + facet_grid(.~.sign) + theme(axis.text.y = element_text(size = 10), text = element_text(size = 12))
gseaplot(gse_2, by = "all", title = gse_2$Description[1], geneSetID = 1)
```